Draft of readme and ipynb content updates
marcos-calvo/ir-dashboard pull request #15
Opened 2022-10-19 18:40 UTC by HeidiSteen

2022-10-23 08:43 UTC, melmatlis requested changes
Thank you @HeidiSteen  for this amazing PR.
The content is so much clearer than it was, really appreciate the time and effort you took into improving our work

2022-10-23 08:43 UTC, melmatlis commented on README.md
> +As a first step, deploy the dashboard to your Application Insights resource. You'll select the blue button below, which prepares a [predefined ARM template](/src/arm/dashboard.template.json), and the
```suggestion
As a first step, deploy the dashboard to your Application Insights resource. You'll select the blue button below, which prepares a [predefined ARM template](/src/arm/dashboard.template.json), and then fill in some properties. The ARM template creates the visualizations and provides the Kusto queries that explore the simulated data.
```

2022-10-23 08:43 UTC, melmatlis commented on README.md
```suggestion
## Contribution
This code is a collaborative effort of CSE & DAI&SL<br>
Huge credit to [@dupuyjs](https://github.com/dupuyjs) for setting up the ARM template and expertise

```

2022-10-23 08:43 UTC, melmatlis commented on README.md
> -This code is a collaborative effort of CSE & DAI&SL<br>
This work is and excerpt from a client project, I would like to keep the contribution to others in the READ.ME file.
I hope it's OK, I moved to the section prior to licensing

2022-10-23 09:10 UTC, melmatlis commented on notebooks/app_insights_sdk_example.ipynb
> +    "  %pip install -r ../requirements.txt\n",
```suggestion
    "  !pip install -r ../requirements.txt\n",
```

2022-10-24 15:59 UTC, HeidiSteen commented on notebooks/app_insights_sdk_example.ipynb
> +    "  %pip install -r ../requirements.txt\n",
I changed this back to how you had it before.  VS Code suggested the alternate syntax, but you know this space best.

2022-10-24 16:28 UTC, HeidiSteen reviewed
@melmatlis I think everything is addressed. I moved the credit up to the intro in the readme (line 15), and spelled out the organization name.  Unless you spot something else, I think the PR is ready.

2022-10-25 06:41 UTC, merged